### PR TITLE
fix: ナビゲーションバー内の画像の破綻修正

### PR DESCRIPTION
**Pull request by tkatsuya**
やるべきタスク
- [ ] サーチバーの配置修正
- [ ] プロジェクト内のレイアウトの一部修正（元と異なるため直す）
- [ ] help-page先の作成（ボタンのみしか配置していない＋ルーティングされていない）

---
This change is [Reviewable](https://reviewable.io/reviews/fabnavi/fabnavi-webclient/12)

### CODE REVIEW

**Comment by hrl7** [comment]
Reviewed 1 of 1 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/components/Player.jsx, line 139 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/12#-Kn359V0zXrI_mAhuXEu:-Kn359V0zXrI_mAhuXEv:b9iirmp) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/746d132868eaa96c9571e8570828c188345f5dbb/src/components/Player.jsx#L139)):*
> ```JSX
> 
>     componentWillMount() {
>       debug(this.props.params.projectId);
> ```

インデントがずれている。なおすか, debugを消そう。

---

*[src/stylesheets/application/application.scss, line 164 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/12#-Kn35NkPgnEUaJePg8Fz:-Kn35NkQl5Ca-8Ebn3P0:byu3jed) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/746d132868eaa96c9571e8570828c188345f5dbb/src/stylesheets/application/application.scss#L164)):*
> ```SCSS
>   //padding-top:5px;
>   //padding-left: 500px;
>   //height: $belt-height;
> ```

不要なら消そう。我々はgitを使っているのだから, いつでも元に戻せる。

---

*[src/stylesheets/application/application.scss, line 168 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/12#-Kn35RiKz63p_I_xQsi-:-Kn35RiKz63p_I_xQsi0:b-ix36cn) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/746d132868eaa96c9571e8570828c188345f5dbb/src/stylesheets/application/application.scss#L168)):*
> ```SCSS
>     position: relative;
>     //right: 0;
>     //margin-right: 400px;
> ```

不要なら消そう

---

*[src/stylesheets/application/application.scss, line 183 at r2](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/12#-Kn35YCnFnyZr4l-ZvaE:-Kn35YCnFnyZr4l-ZvaF:b-gygjom) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/746d132868eaa96c9571e8570828c188345f5dbb/src/stylesheets/application/application.scss#L183)):*
> ```SCSS
>       width: 80%;
>       font-size:12pt;
>       //padding-left: 10px;
> ```

これも不要なら消そう

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/12)*

**Comment by tkatsuya** [comment]
上記四点なおしました。インデントのズレに関してですが、lint通して問題がなかったため何か発生した場合は再度ご連絡ください。

**Comment by hrl7** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/12)*

**Comment by hrl7** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/12)*

**Comment by hrl7** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/12#-:-Kn4eVXwKqSfTJGS2GX4:bnfp4nl)*

**Pull request merged**
