### PR TITLE
Delete change frame & Change frame management by using react-router and redux

### PR DESCRIPTION
**Pull request by fmsuvM**
reducerにあったframe.jsを用いて管理していた部分を全て排除．react-routerとreduxでページ状態を管理するようにした

---
This change is [Reviewable](https://reviewable.io/reviews/fabnavi/fabnavi-webclient/11)

### CODE REVIEW

**Comment by hrl7** [comment]
Reviewed 11 of 16 files at r1, 2 of 3 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/actions/KeyActionCreator.js, line 146 at r3](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn2T9hSJmipCK7kRsj1:-Kn2T9hSJmipCK7kRsj2:b37yo8l) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/2dc14378f6d37a9262877b116379e23f5442b1ca/src/actions/KeyActionCreator.js#L146)):*
> ```JavaScript
> 
> function exitDetail(store, action){
>     console.log('exitDetail');
> ```

console.logは消すかdebugに置き換えよう

---

*[src/actions/KeyActionCreator.js, line 150 at r3](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn2TKHWRK8GlafSgnsW:-Kn2TKHWRK8GlafSgnsX:bucasoj) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/2dc14378f6d37a9262877b116379e23f5442b1ca/src/actions/KeyActionCreator.js#L150)):*
> ```JavaScript
>     action.payload = 'manager';
>     store.dispatch(action);
>     store.dispatch(push('/'));
> ```

detailからもどったときって, 必ず `/` にいくの？
`/myprojects` からdetailへ進んだ場合, 
`/` ではなく `/myprojects` へ戻るのが正しい気がする.
react-router-reduxにはpush以外にも `goBack` とかあるので, 
それらを使うと良さそう

---

*[src/actions/Types.js, line 12 at r3](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn2Tt6mJG3qH5XPICMK:-Kn2Tt6nxvK4BA9gqTEg:b-ipe9qd) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/2dc14378f6d37a9262877b116379e23f5442b1ca/src/actions/Types.js#L12)):*
> ```JavaScript
>     RECEIVE_PROJECT: null,
> 
>     DETAIL_EXIT: null,
> ```

`DETAIL_EXIT` はどういうときに発行されるアクションなのかによるけど, 
`EXIT_DETAIL` とか `EXITED_FROM_DETAIL_PAGE` とかのほうがわかりやすそう

---

*[src/components/FabnaviApp.jsx, line 39 at r3](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn2UVlVlPx2UGLVxA_t:-Kn2UVlVlPx2UGLVxA_u:bdvc1e6) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/2dc14378f6d37a9262877b116379e23f5442b1ca/src/components/FabnaviApp.jsx#L39)):*
> ```JSX
>     const url = window.location.href;
>     const location = createMemoryHistory("/").createLocation();
>     let history = createMemoryHistory(location)
> ```

locationは別に生成しなくても動くので消そう.

---

*[src/components/FabnaviApp.jsx, line 45 at r3](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn2XN1haRvUWqI-1L4s:-Kn2XN1i01YcBPCcuC2U:b-vp8bx1) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/2dc14378f6d37a9262877b116379e23f5442b1ca/src/components/FabnaviApp.jsx#L45)):*
> ```JSX
>         combineReducers({
>             ...reducers, 
>             routing: routerReducer
> ```

combineReducersは, `reducers/index.js` でやる方が綺麗.

---

*[src/components/FabnaviApp.jsx, line 59 at r3](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn2V48v2TO1hRrRviYG:-Kn2V48v2TO1hRrRviYH:b-rpngu5) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/505a6e125a36c3acd2781dd019892268a62c786b/src/components/FabnaviApp.jsx#L59)):*
> ```JSX
>                 <Route component={ProjectList} path="myprojects"/>
>                 <Route component={CreateProject} path="create"/>
>                 <Route component={EditProject} path="edit/:projectId"/>
> ```

EditProjectは消していいの？

---

*[src/components/MenuIcon.jsx, line 17 at r3](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn2W5DBxg6VVTsmZcd-:-Kn2W5DBxg6VVTsmZcd0:bk146ib) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/2dc14378f6d37a9262877b116379e23f5442b1ca/src/components/MenuIcon.jsx#L17)):*
> ```JSX
>         this.onClick = () => {
>             if(this.props.hasOwnProperty('to')) {
>                 store.dispatch(push('/'));
> ```

storeを叩くといろいろわけがわからなくなるので, react-reduxのconnect内でdispatchを使おう

---

*[src/components/MenuIcon.jsx, line 44 at r3](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn2Wpci5N7mTRDdD9UH:-Kn2Wpci5N7mTRDdD9UI:blji49q) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/2dc14378f6d37a9262877b116379e23f5442b1ca/src/components/MenuIcon.jsx#L44)):*
> ```JSX
>                 const url = authWindow.getURL();
>                 if(url.includes('uid') && url.includes('client_id') && url.includes('auth_token')){
>                     // console.log('action');
> ```

不要なconsole.logは消そう

---

*[src/reducers/frame.js, line 10 at r3](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn2X4G1539s7ASc--W-:-Kn2X4G1539s7ASc--W0:b-4halc1) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/2dc14378f6d37a9262877b116379e23f5442b1ca/src/reducers/frame.js#L10)):*
> ```JavaScript
> export default function frameReducer(state = initialState, action) {
>     switch(action.type) {
>         case Act.CHANGE_FRAME:
> ```

`CHANGE_FRAME` 消したならもういらないとおもう

---

*[src/utils/projectUtils.js, line 27 at r3](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn2XYvB4v5eifiM3f_0:-Kn2XYvB4v5eifiM3f_1:blu3f5w) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/2dc14378f6d37a9262877b116379e23f5442b1ca/src/utils/projectUtils.js#L27)):*
> ```JavaScript
>         return src;
>     } catch(e) {
>         // debug('Catnnot get project thumbnail src ', e);
> ```

不要なdebugは消そう

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11)*

**Comment by fmsuvM** [comment]
Review status: 10 of 18 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/actions/KeyActionCreator.js, line 150 at r3](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn2TKHWRK8GlafSgnsW:-Kn38gLCbRmMVtvMe-pA:byfi2zo) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/2dc14378f6d37a9262877b116379e23f5442b1ca/src/actions/KeyActionCreator.js#L150)):*
<details><summary><i>Previously, hrl7 (Zigen) wrote…</i></summary><blockquote>

detailからもどったときって, 必ず `/` にいくの？
`/myprojects` からdetailへ進んだ場合, 
`/` ではなく `/myprojects` へ戻るのが正しい気がする.
react-router-reduxにはpush以外にも `goBack` とかあるので, 
それらを使うと良さそう
</blockquote></details>

`goBack()` はbackbutton branchで使っています
import-fabnavi5からキー操作を排除した後に，全て `goBac()` にする予定です

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11)*

**Comment by hrl7** [comment]
Reviewed 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/components/MenuIcon.jsx, line 17 at r4](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn3REzFWC9dnq1ThteZ:-Kn3REzFWC9dnq1Thte_:b-o1h4sa) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/79ebf9d615015a549e05bc5319e7b5790cc6ce99/src/components/MenuIcon.jsx#L17)):*
> ```JSX
>         this.onClick = () => {
>             if(this.props.hasOwnProperty('to')) {
>                 this.props.goHome()
> ```

`this.props` に `to` が入っていたらかならず `/myprojects` に飛ぶのだろうか？
`<MenuIcon />` がどこで使われているか確認しよう。
もし, すべて `/myprojects` に飛ぶのだとしたらこの `to` という変数名は変えた方がいいし, そうでないのだとしたら, `/myprojects` に飛ばすべきではない

---

*[src/components/MenuIcon.jsx, line 84 at r4](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn3R8zvq3CvHOB0ZSLh:-Kn3R8zvq3CvHOB0ZSLi:butdt11) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/79ebf9d615015a549e05bc5319e7b5790cc6ce99/src/components/MenuIcon.jsx#L84)):*
> ```JSX
>     return {
>         goHome: () => {
>             dispatch(push('/myprojects'))
> ```

必ずしも全て `/myprojects` にいくの？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11)*

**Comment by hrl7** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/components/MenuIcon.jsx, line 18 at r5](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn3d6l7stGYJoZc4jt3:-Kn3d6l80_nIjsn2hRiI:b-3ow62h) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/39977a5fdc77914e4601ec3753ae16161c960607/src/components/MenuIcon.jsx#L18)):*
> ```JSX
>             if(this.props.hasOwnProperty('to')) {
>                 console.log('this.props in MenuIcon.jsx');
>                 console.log(this.props);
> ```

console.logを消そう

---

*[src/components/MenuIcon.jsx, line 23 at r5](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn3entTcafaU7enRQ_p:-Kn3entUerZX5Hpk6diD:b-ve92z3) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/39977a5fdc77914e4601ec3753ae16161c960607/src/components/MenuIcon.jsx#L23)):*
> ```JSX
>                 } else if(this.props.to === 'myprojects'){
>                     this.props.goMyHome();
>                 }
> ```

なんで `this.props.to` をpushに渡さないの。。。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11)*

**Comment by hrl7** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/MenuIcon.jsx, line 17 at r6](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-Kn3lZ9o5Ztj1jC76l9g:-Kn3lZ9p37WSmyEFsKSl:b-ddn3ys) ([raw file](https://github.com/fabnavi/fabnavi-webclient/blob/1ace064fc719017a5ae53714824d37e512bc115e/src/components/MenuIcon.jsx#L17)):*
> ```JSX
>         this.onClick = () => {
>             if(this.props.hasOwnProperty('to')) {
>                 this.props.goTo(this.props.to);
> ```

もうすこし名前かんがえよう。。。

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11)*

**Comment by hrl7** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11)*

**Comment by hrl7** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fabnavi/fabnavi-webclient/11#-:-Kn3r5qqDnLINv1tBpWH:bnfp4nl)*

**Pull request merged**
